services:
  postgres:
    image: postgres
    container_name: postgres_nc
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: ${PG_DATA}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - nova_care
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak_nc
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "9090:8080"
    networks:
      - nova_care
    command:
      - "start-dev"
volumes:
  postgres:
    driver: local
networks:
  nova_care:
    driver: bridge